import { motion } from 'framer-motion';
import { ArrowLeft, ExternalLink, Sparkles } from 'lucide-react';
import RevealOnScroll from './components/RevealOnScroll';
import MagneticButton from './components/MagneticButton';
const projects = [
  { title: "SIMAQ Darussalam", description: "Platform digital untuk manajemen pembelajaran Al-Qur'an di Markaz Qur'an Darussalam.", tags: ["React","Tailwind CSS","Vercel","Database"], link: "https://simaq.vercel.app", image: "https://placehold.co/600x400/1e3a8a/white?text=SIMAQ", gradient: "from-blue-600 to-indigo-600", fullDesc: "SIMAQ (Sistem Informasi Manajemen Al-Qur'an) adalah aplikasi modern yang membantu pengelolaan hafalan, setoran, dan evaluasi santri secara digital." },
  { title: "PUSPITA INDAH", description: "Lembaga Pelatihan Kerja spesialis Jasa Rias Pengantin, Dekorasi, Catering, Tata Kecantikan, dan Tata Busana.", tags: ["SEO","Website Profil","Google Indexed","Responsive"], link: "https://www.puspitaindah.com", image: "https://placehold.co/600x400/ec4899/white?text=PUSPITA+INDAH", gradient: "from-rose-500 to-orange-500", fullDesc: "Website resmi PUSPITA INDAH yang sudah terindeks di Google, menampilkan layanan pelatihan, galeri, dan informasi kontak lengkap." }
];
export default function PortfolioPage() {
  const goBack = () => window.location.href = '/';
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-white"><nav className="fixed top-0 left-0 w-full z-50 bg-white/80 backdrop-blur-md border-b border-gray-200"><div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between"><div className="flex items-center gap-3 cursor-pointer" onClick={goBack}><div className="w-8 h-8 bg-gradient-to-br from-blue-700 to-cyan-500 rounded-xl flex items-center justify-center"><span className="text-white font-bold text-lg">G</span></div><span className="font-semibold text-xl text-gray-800">goding</span></div><MagneticButton onClick={goBack} className="px-5 py-2 bg-gradient-to-r from-blue-600 to-cyan-500 text-white rounded-xl text-sm font-semibold flex items-center gap-2"><ArrowLeft className="w-4 h-4" /> Kembali ke Beranda</MagneticButton></div></nav>
      <main className="pt-24 pb-20 px-6 max-w-7xl mx-auto"><RevealOnScroll componentName="portfolio" direction="up" className="text-center mb-16"><div className="inline-flex items-center gap-2 bg-blue-100 text-blue-800 text-sm font-semibold px-4 py-2 rounded-full mb-4"><Sparkles className="w-4 h-4" /> PORTFOLIO KAMI</div><h1 className="text-4xl sm:text-5xl md:text-6xl font-bold tracking-tighter text-gray-800">Proyek yang <span className="gradient-text">Telah Kami Selesaikan</span></h1><p className="mt-4 text-lg text-zinc-600 max-w-2xl mx-auto">Setiap proyek adalah bukti komitmen kami dalam menghadirkan solusi digital terbaik.</p></RevealOnScroll>
      <div className="grid md:grid-cols-2 gap-8">{projects.map((project, idx) => (<RevealOnScroll key={idx} delay={0.2+idx*0.15} direction={idx===0?"left":"right"}><motion.div whileHover={{ y: -8 }} className="bg-white rounded-2xl md:rounded-3xl shadow-xl overflow-hidden border border-gray-100 hover:shadow-2xl transition-all duration-300"><div className={`relative h-56 bg-gradient-to-br ${project.gradient} flex items-center justify-center`}><img src={project.image} alt={project.title} className="w-full h-full object-cover opacity-80" /><div className="absolute inset-0 bg-black/30 flex items-center justify-center"><span className="text-white text-4xl font-bold drop-shadow-lg">{project.title.split(' ')[0]}</span></div></div><div className="p-6 md:p-8"><h2 className="text-2xl md:text-3xl font-bold text-gray-800 mb-3">{project.title}</h2><p className="text-zinc-600 mb-4">{project.description}</p><p className="text-sm text-zinc-500 mb-4 border-l-4 border-blue-400 pl-3 italic">{project.fullDesc}</p><div className="flex flex-wrap gap-2 mb-6">{project.tags.map((tag,i)=><span key={i} className="text-xs font-medium px-3 py-1 rounded-full bg-gray-100 text-gray-700">{tag}</span>)}</div><MagneticButton as="a" href={project.link} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 text-blue-600 font-semibold hover:gap-3 transition-all group">Kunjungi Website <ExternalLink className="w-4 h-4" /></MagneticButton></div></motion.div></RevealOnScroll>))}</div></main>
    </div>
  );
}
